# Generated by Django 3.2.3 on 2021-06-12 15:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.PositiveIntegerField(
                max_length=64,
                validators=[
                    django.core.validators.MinValueValidator(1)],
                verbose_name='Единицы измерения'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(
                verbose_name='Время приготовления(мин)'),
        ),
    ]
