# Generated by Django 3.2.3 on 2021-06-13 15:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_ingredient_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1)],
                verbose_name='Единицы измерения'),
        ),
    ]
