# Generated by Django 3.2.3 on 2021-06-14 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_remove_recipe_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='name',
            new_name='title',
        ),
    ]
