# Generated by Django 3.2.3 on 2021-06-14 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_rename_ingredient_ingredients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredients',
            old_name='unit',
            new_name='dimension',
        ),
    ]
