# Generated by Django 3.2.3 on 2021-06-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_rename_unit_ingredients_dimension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='dimension',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Единицы измерения'),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Название'),
        ),
    ]
