# Generated by Django 3.2.3 on 2021-06-17 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0020_alter_subscription_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglist',
            name='user',
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='author',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='user_sl',
                to='auth.user',
                verbose_name='Автор'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='recipe',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='recipe_sl',
                to='recipes.recipe',
                verbose_name='Рецепт'),
        ),
    ]
