# Generated by Django 3.2.3 on 2021-06-17 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0027_alter_recipe_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='user',
            new_name='author',
        ),
    ]
