# Generated by Django 3.2.3 on 2021-06-17 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0028_rename_user_favorite_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='author',
            new_name='user',
        ),
    ]
