# Generated by Django 3.2.3 on 2021-06-18 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0029_rename_author_favorite_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientrecipe',
            name='recipe',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='ingredients_recipe',
                to='recipes.recipe',
                verbose_name='Рецепт'),
        ),
    ]
