# Generated by Django 3.2.3 on 2021-06-18 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0030_alter_ingredientrecipe_recipe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Ingredient',
        ),
    ]
