# Generated by Django 3.2.3 on 2021-06-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0033_auto_20210618_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientrecipe',
            name='value',
            field=models.FloatField(max_length=32, verbose_name='Количество'),
        ),
    ]
