# Generated by Django 3.2.3 on 2021-06-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0034_alter_ingredientrecipe_value'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(
                fields=('user', 'author'), name='unique_follow'),
        ),
    ]
